const fs = require('fs');

const zhDict = {
    "MISSING_ZH_nav.brand": "NS Matrix",
    "MISSING_ZH_nav.toggleTheme": "切换主题",
    "MISSING_ZH_nav.toggleLanguage": "English",
    "MISSING_ZH_nav.search": "搜索...",
    "MISSING_ZH_nav.favorites": "我的收藏",
    "MISSING_ZH_nav.cart": "购物袋",
    "MISSING_ZH_nav.profile": "个人主页",
    "MISSING_ZH_nav.avatar": "用户头像",
    "MISSING_ZH_nav.searchProducts": "搜索商品、创客...",
    "MISSING_ZH_nav.openProfile": "打开个人资料",
    "MISSING_ZH_nav.login": "登录",

    "MISSING_ZH_about.hero.title": "由理念到现实的飞跃",
    "MISSING_ZH_about.hero.subtitle": "我们通过 ZeroClaw 智能体架构，让零碎的创客火花，在极简美学中聚合成改变行业的商品。",
    "MISSING_ZH_about.story.paragraphOne": "这不仅仅是一个商城。这是一个连接全球创客大脑和消费者心智的枢纽。",
    "MISSING_ZH_about.story.paragraphTwo": "我们坚信数字力量能重塑制造业边界。无论是 3D 打印、算法模型，还是硬件极客的奇思妙想，都可以在这找到他们的知音。",
    "MISSING_ZH_about.architecture.title": "ZeroClaw 架构设计",
    "MISSING_ZH_about.features.research.title": "深度市场调研",
    "MISSING_ZH_about.features.research.body": "多模态 AI 智能体 24 小时巡航全球需求数据，捕捉下一波红利。",
    "MISSING_ZH_about.features.data.title": "数据清洗矩阵",
    "MISSING_ZH_about.features.data.body": "剔除结构化噪声，提供纯净如水的商业决策参考点。",
    "MISSING_ZH_about.features.strategy.title": "自动化演进策略",
    "MISSING_ZH_about.features.strategy.body": "实时生成原型和代码，降低 80% 验证成本，打造极致 MVP。",
    "MISSING_ZH_about.features.execution.title": "敏捷生产执行",
    "MISSING_ZH_about.features.execution.body": "通过云端对接柔型供应链极速接单打样，缩短交付链路。",
    "MISSING_ZH_about.horizon.title": "展望未来",
    "MISSING_ZH_about.horizon.body": "当我们用数字消除壁垒时，每一个普通人都能成为伟大的创作者。这只是我们征程的起点。",
    "MISSING_ZH_about.footer.copyright": "© 2026 Smart-JA NS. 保留所有权利.",
    "MISSING_ZH_about.footer.version": "ZeroClaw v1.4.2 运行中",

    "MISSING_ZH_assistant.headerEyebrow": "AI 导购核心",
    "MISSING_ZH_assistant.title": "AI 悬浮助理",
    "MISSING_ZH_assistant.status.loading": "正在同步全局商品谱系...",
    "MISSING_ZH_assistant.status.synced": "已挂载 {count} 个活跃服务",
    "MISSING_ZH_assistant.actions.refresh": "重新挂载",
    "MISSING_ZH_assistant.actions.viewDetails": "点击预览",
    "MISSING_ZH_assistant.actions.purchasing": "生成订单中...",
    "MISSING_ZH_assistant.actions.buyShort": "选购 {title}",
    "MISSING_ZH_assistant.guideLabel": "NS AI 导购",
    "MISSING_ZH_assistant.inputPlaceholder": "描述你的痛点，例如：我刚养了猫，有什么推荐？",

    "MISSING_ZH_search.placeholder": "搜寻一切未知的可能...",
    "MISSING_ZH_search.recent": "近期搜索",
    "MISSING_ZH_search.clear": "清空记录",
    "MISSING_ZH_search.noRecent": "暂无足迹",
    "MISSING_ZH_search.trending": "全网热点",
    "MISSING_ZH_search.rising": "飙升趋势",
    "MISSING_ZH_search.new": "新灵感",
    "MISSING_ZH_search.tipTitle": "AI 查询贴士",
    "MISSING_ZH_search.tipBody": "尝试用自然语言（如：“适合重度失眠患者的科技产品”）来进行模糊检索！",

    "MISSING_ZH_aiLab.title": "A.I. 创客实验室",
    "MISSING_ZH_aiLab.shortTitle": "AI Lab",
    "MISSING_ZH_aiLab.actions.export": "导出白皮书",
    "MISSING_ZH_aiLab.actions.history": "追溯记录",
    "MISSING_ZH_aiLab.actions.newProject": "+ 新概念设想",
    "MISSING_ZH_aiLab.actions.nextStage": "开启下一步推进",
    "MISSING_ZH_aiLab.agentChain": "当前驱动链：ZeroClaw",
    "MISSING_ZH_aiLab.poweredBy": "由 NS Matrix 强力驱动",
    "MISSING_ZH_aiLab.noHistory": "系统记录为空",
    "MISSING_ZH_aiLab.stageLabel": "进程标识",
    "MISSING_ZH_aiLab.inputThinking": "主脑逻辑推演中...",
    "MISSING_ZH_aiLab.inputPlaceholder": "抛开束缚，输入你脑海中的任何极致产品构想...",
    "MISSING_ZH_aiLab.disclaimer": "AI 生成的大纲和建议需要您的亲自校验，请勿盲目直接投入量产。",

    "MISSING_ZH_investor.hero.eyebrow": "GLOBAL NETWORK DATA",
    "MISSING_ZH_investor.hero.title": "投资者宏观引擎大屏",
    "MISSING_ZH_investor.hero.description": "穿透商业噪音，实时洞察全平台生态流动与创变趋势。",
    "MISSING_ZH_investor.metrics.financing": "平台历史总融资 (¥)",
    "MISSING_ZH_investor.metrics.projects": "孵化流转项目数",
    "MISSING_ZH_investor.metrics.coaches": "月度大盘总收益 (¥)",
    "MISSING_ZH_investor.metrics.growth": "活跃转化率",
    "MISSING_ZH_investor.radar.eyebrow": "ECOSYSTEM RADAR",
    "MISSING_ZH_investor.radar.title": "前沿赛道热度光谱",
    "MISSING_ZH_investor.radar.badge": "高频更新",
    "MISSING_ZH_investor.leaderboard.eyebrow": "TOP MAKERS RANK",
    "MISSING_ZH_investor.leaderboard.title": "顶级创客战力榜",
    "MISSING_ZH_investor.leaderboard.badge": "LIVE",
    "MISSING_ZH_investor.leaderboard.rank": "名次",
    "MISSING_ZH_investor.leaderboard.gmv": "口碑评级",
    "MISSING_ZH_investor.leaderboard.orders": "信誉积分",
    "MISSING_ZH_investor.routes.eyebrow": "DATA LIFECYCLE",
    "MISSING_ZH_investor.routes.title": "数据流动图谱",
    "MISSING_ZH_investor.narrative.eyebrow": "NARRATIVE",
    "MISSING_ZH_investor.narrative.title": "智能纪元的下一站",
    "MISSING_ZH_investor.narrative.body": "我们的技术底座已经准备好迎接百万级并发。无论是从代码到模具，还是从需求到交割，这一切都已在系统中顺利流转闭环。",

    "MISSING_ZH_product.actions.backToMarket": "返回全景市场",
    "MISSING_ZH_product.actions.refresh": "重新载入数据",
    "MISSING_ZH_product.actions.tryAgain": "返回重试",
    "MISSING_ZH_product.actions.buyNow": "立 即 买 断",
    "MISSING_ZH_product.actions.addToCart": "加入愿望单",
    "MISSING_ZH_product.actions.saved": "已收藏",
    "MISSING_ZH_product.actions.save": "收 藏",
    "MISSING_ZH_product.actions.backProject": "支 持 创 想",
    "MISSING_ZH_product.errorEyebrow": "ERROR 404",
    "MISSING_ZH_product.errorTitle": "请求的构想物不存在或已离线",
    "MISSING_ZH_product.hero.eyebrow": "VISION PROTOTYPE",
    "MISSING_ZH_product.hero.renderStage": "概念渲染完成，实体筹备中。",
    "MISSING_ZH_product.crowdfunding.eyebrow": "SUPPORT MAKERS",
    "MISSING_ZH_product.crowdfunding.title": "参与这场共创",
    "MISSING_ZH_product.crowdfunding.wave": "加入早期极客网络",
    "MISSING_ZH_product.crowdfunding.filled": "达成率",
    "MISSING_ZH_product.crowdfunding.pledged": "当前募集认购",
    "MISSING_ZH_product.crowdfunding.goal": "目标里程碑",
    "MISSING_ZH_product.crowdfunding.backers": "节点支持者",
    "MISSING_ZH_product.story.eyebrow": "BEHIND THE SCENES",
    "MISSING_ZH_product.story.title": "起源与核心逻辑",
    "MISSING_ZH_product.specs.views": "全网曝光",
    "MISSING_ZH_product.specs.sales": "已出售/支持",
    "MISSING_ZH_product.specs.launchData": "启动节点",
    "MISSING_ZH_product.specs.price": "兑换价"
};

const enDict = {
    "MISSING_EN_nav.brand": "NS Matrix",
    "MISSING_EN_nav.toggleTheme": "Toggle Theme",
    "MISSING_EN_nav.toggleLanguage": "中文",
    "MISSING_EN_nav.search": "Search for limits...",
    "MISSING_EN_nav.favorites": "Favorites",
    "MISSING_EN_nav.cart": "Bag",
    "MISSING_EN_nav.profile": "Profile",
    "MISSING_EN_nav.avatar": "Avatar",
    "MISSING_EN_nav.searchProducts": "Search concepts, makers...",
    "MISSING_EN_nav.openProfile": "Open Profile",
    "MISSING_EN_nav.login": "Sign In",

    "MISSING_EN_about.hero.title": "Leap from Idea to Reality",
    "MISSING_EN_about.hero.subtitle": "Through our ZeroClaw architecture, we converge scattered maker sparks into world-changing products with minimalist aesthetics.",
    "MISSING_EN_about.story.paragraphOne": "This is more than a marketplace. It's a nexus connecting global maker brains with consumer minds.",
    "MISSING_EN_about.story.paragraphTwo": "We firmly believe digital power redesigns manufacturing borders. Whether it's 3D printing or AI modeling, radical ideas find their audience here.",
    "MISSING_EN_about.architecture.title": "ZeroClaw Architecture",
    "MISSING_EN_about.features.research.title": "Deep Market Research",
    "MISSING_EN_about.features.research.body": "Multi-modal AI agents cruise global data 24/7 to predict the next wave.",
    "MISSING_EN_about.features.data.title": "Data Refining Matrix",
    "MISSING_EN_about.features.data.body": "Eliminating structural noise to provide pristine business decision points.",
    "MISSING_EN_about.features.strategy.title": "Auto-Evolution Strategy",
    "MISSING_EN_about.features.strategy.body": "Real-time prototyping reducing MVP validation costs by 80%.",
    "MISSING_EN_about.features.execution.title": "Agile Execution",
    "MISSING_EN_about.features.execution.body": "Connecting flexible supply chains in the cloud for ultra-fast delivery.",
    "MISSING_EN_about.horizon.title": "Into the Horizon",
    "MISSING_EN_about.horizon.body": "When we dissolve barriers with code, anyone can become a great creator. This is merely the beginning of our journey.",
    "MISSING_EN_about.footer.copyright": "© 2026 Smart-JA NS. All rights reserved.",
    "MISSING_EN_about.footer.version": "ZeroClaw v1.4.2 Running",

    "MISSING_EN_assistant.headerEyebrow": "AI CONCIERGE",
    "MISSING_EN_assistant.title": "AI Sales Assistant",
    "MISSING_EN_assistant.status.loading": "Syncing global catalog...",
    "MISSING_EN_assistant.status.synced": "Mounted {count} active services",
    "MISSING_EN_assistant.actions.refresh": "Remount",
    "MISSING_EN_assistant.actions.viewDetails": "Inspect",
    "MISSING_EN_assistant.actions.purchasing": "Processing...",
    "MISSING_EN_assistant.actions.buyShort": "Get {title}",
    "MISSING_EN_assistant.guideLabel": "NS AI Guide",
    "MISSING_EN_assistant.inputPlaceholder": "Describe your needs, e.g., 'Looking for a gift for my cat...'",

    "MISSING_EN_search.placeholder": "Search the unknown...",
    "MISSING_EN_search.recent": "Recent Steps",
    "MISSING_EN_search.clear": "Clear Logs",
    "MISSING_EN_search.noRecent": "No footprints",
    "MISSING_EN_search.trending": "Global Heat",
    "MISSING_EN_search.rising": "Velocity",
    "MISSING_EN_search.new": "New Sparks",
    "MISSING_EN_search.tipTitle": "AI Search Tip",
    "MISSING_EN_search.tipBody": "Try natural language strings like 'tech gadgets for heavy insomniacs'!",

    "MISSING_EN_aiLab.title": "A.I. Maker Lab",
    "MISSING_EN_aiLab.shortTitle": "AI Lab",
    "MISSING_EN_aiLab.actions.export": "Export Plan",
    "MISSING_EN_aiLab.actions.history": "Trace Logs",
    "MISSING_EN_aiLab.actions.newProject": "+ New Hypothesis",
    "MISSING_EN_aiLab.actions.nextStage": "Initiate Next Stage",
    "MISSING_EN_aiLab.agentChain": "Active Chain: ZeroClaw",
    "MISSING_EN_aiLab.poweredBy": "Engineered by NS Matrix",
    "MISSING_EN_aiLab.noHistory": "Database empty",
    "MISSING_EN_aiLab.stageLabel": "Process Stage",
    "MISSING_EN_aiLab.inputThinking": "Core computing...",
    "MISSING_EN_aiLab.inputPlaceholder": "Release constraints, type any extreme product concept in your mind...",
    "MISSING_EN_aiLab.disclaimer": "AI outputs require human validation. Do not blindly deploy to production.",

    "MISSING_EN_investor.hero.eyebrow": "GLOBAL NETWORK DATA",
    "MISSING_EN_investor.hero.title": "Investor Macro Engine",
    "MISSING_EN_investor.hero.description": "Pierce through commercial noise and track the fluid dynamics of the global maker ecosystem in real-time.",
    "MISSING_EN_investor.metrics.financing": "Lifetime Funding (¥)",
    "MISSING_EN_investor.metrics.projects": "Incubating Nodes",
    "MISSING_EN_investor.metrics.coaches": "Total Gross Revenue (¥)",
    "MISSING_EN_investor.metrics.growth": "Active Conversion",
    "MISSING_EN_investor.radar.eyebrow": "ECOSYSTEM RADAR",
    "MISSING_EN_investor.radar.title": "Sector Heat Spectrum",
    "MISSING_EN_investor.radar.badge": "SYNC",
    "MISSING_EN_investor.leaderboard.eyebrow": "TOP MAKERS RANK",
    "MISSING_EN_investor.leaderboard.title": "Maker Tier Hierarchy",
    "MISSING_EN_investor.leaderboard.badge": "LIVE",
    "MISSING_EN_investor.leaderboard.rank": "Rank",
    "MISSING_EN_investor.leaderboard.gmv": "Validation",
    "MISSING_EN_investor.leaderboard.orders": "Reputation EXP",
    "MISSING_EN_investor.routes.eyebrow": "DATA LIFECYCLE",
    "MISSING_EN_investor.routes.title": "Data Flow Topology",
    "MISSING_EN_investor.narrative.eyebrow": "NARRATIVE",
    "MISSING_EN_investor.narrative.title": "The Next Stop in the Smart Epoch",
    "MISSING_EN_investor.narrative.body": "Our foundation is ready for million-level concurrency. From code to molds, ideas flow seamlessly into closed delivery loops.",

    "MISSING_EN_product.actions.backToMarket": "Return to Market",
    "MISSING_EN_product.actions.refresh": "Reload Data",
    "MISSING_EN_product.actions.tryAgain": "Try Again",
    "MISSING_EN_product.actions.buyNow": "B U Y  N O W",
    "MISSING_EN_product.actions.addToCart": "Add to Wishlist",
    "MISSING_EN_product.actions.saved": "Acquired",
    "MISSING_EN_product.actions.save": "A c q u i r e",
    "MISSING_EN_product.actions.backProject": "B A C K  P R O J E C T",
    "MISSING_EN_product.errorEyebrow": "ERROR 404",
    "MISSING_EN_product.errorTitle": "Conceptual artifact missing or offline",
    "MISSING_EN_product.hero.eyebrow": "VISION PROTOTYPE",
    "MISSING_EN_product.hero.renderStage": "Render completed. Hardware prep engaged.",
    "MISSING_EN_product.crowdfunding.eyebrow": "SUPPORT MAKERS",
    "MISSING_EN_product.crowdfunding.title": "Fuel the Innovation",
    "MISSING_EN_product.crowdfunding.wave": "Join the early geek net",
    "MISSING_EN_product.crowdfunding.filled": "Quota Met",
    "MISSING_EN_product.crowdfunding.pledged": "Current Pledged",
    "MISSING_EN_product.crowdfunding.goal": "Target Milestone",
    "MISSING_EN_product.crowdfunding.backers": "Network Nodes",
    "MISSING_EN_product.story.eyebrow": "BEHIND THE SCENES",
    "MISSING_EN_product.story.title": "Genesis & Core Logic",
    "MISSING_EN_product.specs.views": "Global Exp",
    "MISSING_EN_product.specs.sales": "Transactions",
    "MISSING_EN_product.specs.launchData": "Boot Date",
    "MISSING_EN_product.specs.price": "Pledge Unit"
};

let zhStr = fs.readFileSync('src/locales/zh.json', 'utf8');
let enStr = fs.readFileSync('src/locales/en.json', 'utf8');

for (let [key, val] of Object.entries(zhDict)) {
    zhStr = zhStr.split('"' + key + '"').join('"' + val + '"');
}

for (let [key, val] of Object.entries(enDict)) {
    enStr = enStr.split('"' + key + '"').join('"' + val + '"');
}

// Any missing ones to defaults
zhStr = zhStr.replace(/"MISSING_ZH_([^"]+)"/g, '"$1"');
enStr = enStr.replace(/"MISSING_EN_([^"]+)"/g, '"$1"');

fs.writeFileSync('src/locales/zh.json', zhStr);
fs.writeFileSync('src/locales/en.json', enStr);

console.log("Translation injection complete.");
